### PR TITLE
issue #123 : UpdateTasksService/update tasks in github

### PR DESCRIPTION
**Pull request by Mayuresh94**

### CODE REVIEW

**Review by szirbucz — CHANGES_REQUESTED** [review]

**Comment by szirbucz** [comment]
@Mayuresh94 please set your repository public, since we turned the TaskMarket as a public project. It causes that we can't update your branches from the Pull Request.

**Comment by Mayuresh94** [comment]
> @Mayuresh94 please set your repository public, since we turned the TaskMarket as a public project. It causes that we can't update your branches from the Pull Request.

It's already set to public

**Comment by szirbucz** [comment]
Please update the branch, it seems I've lost my rights for it

**Comment by magwas** [comment]
me too...

**Comment by Mayuresh94** [comment]
"Update branch" button does nothing!

**Comment by Mayuresh94** [comment]
re-issued pull request due to access problems.

**Pull request closed without merging**
