### PR TITLE
re-issued for #123 : UpdateTasksService/update tasks in github

### LINKED ISSUE #123: UpdateTasksService/update tasks in github
Behaviour: UpdateTasksService/update tasks in github
Milestone: Basic github integration

Behaviour description:

each tasks are updated on github after they are updated based on the project model, usine g UpdateGithubIssueService

that service updates the issue according to the fields of the task

Annotations for the test cases:

    @TestedBehaviour("update tasks in github")
    @TestedService("UpdateTasksService")

The production code is at com.kodekonveyor.market.tasks.UpdateTasksService.java
The testbase is at com.kodekonveyor.market.tasks.UpdateTasksServiceTestBase.java
The testcase is at com.kodekonveyor.market.tasks.UpdateTasksServiceUpdateTasksInGithubTest.java

The service:
                
UpdateTasksService
[UpdateTasksService](https://repository.kodekonveyor.com/TaskMarket/kode-konveyor/develop/index.html#97c102eb-d49f-4dd6-bdd0-3ff93ddea1cb)
    

How to work:
* identify what of the above is relevant to your service
* come up with a test about the relevant part
  * create a new empty test
  * make sure that the test description is understandable for the end user
  * put it to @DisplayName annotation for the test
  * write the test according to the test description
  * see the test fail in the right way
  * write the production code needed to pass the test, and no more
  * see the test pass
  * get rid of any PMD violations, comments and other problems in the code
  * see that all tests pass
* repeat until you covered all the relevant parts of the behaviour
* submit your pull request against the milestone of the task

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on [our discord channel](https://discord.gg/CkW6bvp) or ask your mentor.

### PR DESCRIPTION
**Pull request by Mayuresh94**
re-issued due to pull request access problems for previous PR.

### CODE REVIEW

**Comment by magwas** [comment]
I see new code but no new tests. Help me figure out what happened.

**Comment by magwas** [comment]
We also have the issuetoken build error.

**Comment by Mayuresh94** [comment]
> 
> 
> I see new code but no new tests. Help me figure out what happened.

tests verifying UpdateGithubIssueService  is called after tasks are updated.

**Comment by Mayuresh94** [comment]
> 
> 
> We also have the issuetoken build error.

What should be done to fix it?

**Comment by magwas** [comment]
Please call me to help me figure out why do we have so much tests for that couple of lines of code.

**Review by szirbucz — APPROVED** [review]
testcases=2

**Pull request merged**
